# 设置 gin 的运行模式，支持 debug, release, test; release 会屏蔽调试信息，官方建议生产环境中使用
system:
  run_model: "debug"
  port: 9595


mysql:
  username: "root"
  password: "root"
  uri: "127.0.0.1:3306"
  database: "go-demo"
  config: "charset=utf8mb4&parseTime=True"


log:
  prefix: '[simple-cloud-storage]'
  log-file: true
  stdout: 'DEBUG'
  file: 'ERROR'